spotify.df <- read.csv("spotify_60_70_80 dataset.csv")
head(spotify80.df)
spotify80.df <- spotify80.df[-20]
spotify80.df <- spotify80.df[,-1:-3]
head(spotify80.df)
nrow(spotify80.df)
spotify80.df$key <- factor(spotify80.df$key)
levels(spotify80.df$key)
levels(spotify80.df$key)<- c("C","C#","D","D#","E","F","F#","G","G#","A","A#","B")
str(spotify80.df$key)
spotify80.df$key <- relevel(spotify80.df$key, ref = "C")
spotify80.df$mode <- factor(spotify80.df$mode)
levels(spotify80.df$mode)<-c("Minor","Major")
str(spotify80.df$mode)
spotify80.df$mode <- relevel(spotify80.df$mode, ref = "Minor")
spotify80.df$time_signature <- factor(spotify80.df$time_signature)
levels(spotify80.df$time_signature)
spotify80.df$time_signature<- relevel(spotify80.df$time_signature, ref="4")
set.seed(100)
train.index <- sample(1:nrow(spotify80.df), nrow(spotify80.df)*0.7)
train.df <- spotify80.df[train.index,]
valid.df <- spotify80.df[-train.index,]
logit.reg <- glm(target ~ ., data = train.df, family = "binomial")
summary(logit.reg)
head(valid.df)
logit.reg.pred <- predict(logit.reg, valid.df,  type = "response")
logit.reg.pred
library(pROC)
r <- roc(valid.df$target, logit.reg.pred)
plot.roc(r)
coords(r, x = "best")
pred <- ifelse(logit.reg.pred>0.5039852,1,0)
library(caret)
confusionMatrix(factor(pred), factor(valid.df$target), positive = "1")